### ISSUE TITLE
The static method 'downloadFile' can't be accessed through an instance.

### ISSUE THREAD

**Issue by prakasharyaman** [abdallah-odeh/flutter_files_downloader#1]
The static method 'downloadFile' can't be accessed through an instance.
Try using the class 'FileDownloader' to access the method
<img width="407" alt="image" src="https://user-images.githubusercontent.com/63445447/169645458-5baf2431-7772-47ba-8f89-16fcc63f835b.png">
if i use the suggested way
<img width="382" alt="image" src="https://user-images.githubusercontent.com/63445447/169645491-a0081579-e134-4b8a-a55c-7ccc3e4bae6d.png">
The app crashes by showing fatal exception
<img width="749" alt="image" src="https://user-images.githubusercontent.com/63445447/169645547-279400f7-e4c2-47e7-8566-b809576c589e.png">

<img width="629" alt="image" src="https://user-images.githubusercontent.com/63445447/169645543-3365642e-d266-4134-b34b-b7882759caeb.png">
Developing for android 12 though

**Comment by abdallah-odeh** [comment]
Thank you for the feedback, 
- Did you try to download the file via the example?
- Can you provide me with the file url that you are trying to download?
I am trying to reproduce this bug
Thank you in advance.

**Comment by prakasharyaman** [comment]
the example works just fine 
i think it's the problem with threads , their memory might be full
let me try by embedding the example in my code and get back to you

**Comment by abdallah-odeh** [comment]
Working on this bug, will keep you updated, 
Thank you for reporting the bug.

**Comment by prakasharyaman** [comment]
@abdallah-odeh could you try to reproduce it ?
i think this might be a problem with threads

**Comment by abdallah-odeh** [comment]
I'm trying to reproduce it, currently creating an AVD with android 12 to see if it's OS issue

**Comment by prakasharyaman** [comment]
> I'm trying to reproduce it, currently creating an AVD with android 12 to see if it's OS issue

the fact that your example worked completely fine in the same app means it might not be an os issue ..
it most probably is an extra workload issue

**Comment by abdallah-odeh** [comment]
The issue is with download file instance, when it's finished downloading, the instance that supposed to return the result is **null**,
It might be a Threads issue!
if you can provide me with a small project that does you "downloading files" logic it will be highly appreciated, in the mean time, I'm trying to reproduce it in my own projects

**Comment by abdallah-odeh** [comment]
The issue is temporarily solved, could not reproduce it but found the bug
upgrade the library version to **1.0.12** will solve your issue
but if you provide me with a small project that does the same bug I will grateful

if the issue is solved close the bug or tell me to close it, if it persists please let me know

**Comment by prakasharyaman** [comment]
> The issue is temporarily solved, could not reproduce it but found the bug upgrade the library version to **1.0.12** will solve your issue but if you provide me with a small project that does the same bug I will grateful also, can you please provide me with the result of the command **flutter --version**
> 
> if the issue is solved close the bug or tell me to close it, if it persists please let me know

i will try to reproduce it in another app so i can share the code with you ...
meanwhile what was the error that was causing this ? any Idea ?

**Comment by abdallah-odeh** [comment]
The **onDownloadCompleted** call back was called on null,
I really don't know how is that possible as it is assigned once the download task is created,
It actually might be because one the libraries you use in your app, can you please copy and paste the libraries list you are importing in your **pubspec.yaml**?
and the output of **flutter --version** will be appreciated.

**Comment by prakasharyaman** [comment]
libraries used :
 cupertino_icons: ^1.0.2
  get: ^4.6.1
  flex_color_scheme: ^5.0.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_storage: ^10.2.8
  firebase_messaging: ^11.2.7
  firebase_analytics: ^9.1.1
  firebase_crashlytics: ^2.6.3
  animated_text_kit: ^4.2.1
  get_storage: ^2.0.3
  cloud_firestore: ^3.1.13
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  simple_animations: ^4.0.1
  visibility_detector: ^0.2.2
  flashy_tab_bar2: ^0.0.4
  dropdown_button2: ^1.4.0
  image_downloader: ^0.31.0
  share_plus: ^4.0.4
  settings_ui: ^2.0.2  
  url_launcher: ^6.1.0
  awesome_notifications: ^0.6.21
  flutter_native_splash: ^2.1.6
  loading_animation_widget: ^1.1.0+3
  video_player: ^2.4.0
  inview_notifier_list: ^3.0.0
  flutter_downloader: ^1.7.3
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  new_version: ^0.3.0
  wakelock: ^0.6.1+2
  flutter_file_downloader: ^1.0.12
stacktrace of error using crashlytics are : 
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.otft.chomu (has extras) } in com.example.flutter_file_downloader.core.DownloadCompleterBroadcast@96a6b86
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1689)
       at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
and 
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
       at com.example.flutter_file_downloader.core.DownloadCompleterBroadcast.onReceive(DownloadCompleterBroadcast.java:44)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1679)
       at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by abdallah-odeh** [comment]
Is the bug still showing? if so please try to 
- kill the app
- flutter clean
- run the app
if it still showing please let me know

**Comment by prakasharyaman** [comment]
could it be caused by `  flutter_downloader: ^1.7.3`
or `  image_downloader: ^0.31.0`
i will run the app to with  
  
 ` flutter_file_downloader: ^1.0.13`
to see if it works

**Comment by prakasharyaman** [comment]
so good news , the app doesn't crash now but i'm still getting 
`I/flutter (31589): Downloading meme
I/flutter (31589): https://i.redd.it/tc7hwdbhun091.jpg
D/CompatibilityChangeReporter(31589): Compat change id reported: 78294732; UID 10291; state: DISABLED
W/System.err(31589): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
W/System.err(31589):    at com.example.flutter_file_downloader.core.DownloadCompleterBroadcast.onReceive(DownloadCompleterBroadcast.java:45)
W/System.err(31589):    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1679)
W/System.err(31589):    at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
W/System.err(31589):    at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(31589):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(31589):    at android.os.Looper.loopOnce(Looper.java:201)
W/System.err(31589):    at android.os.Looper.loop(Looper.java:288)
W/System.err(31589):    at android.app.ActivityThread.main(ActivityThread.java:7870)
W/System.err(31589):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(31589):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err(31589):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/TransportRuntime.CctTransportBackend(31589): Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
I/TransportRuntime.CctTransportBackend(31589): Status Code: 200`
 is it normal ?

**Comment by abdallah-odeh** [comment]
Yes, you should see the file downloaded to your downloads directory, and the path will be returned to your flutter code, that is the temporary solution for now until if find the real cause of the bug

**Comment by abdallah-odeh** [comment]
Tried to import all the libraries you sent and it still not showing the error,
is you project's native code Java or Kotlin?
is your MainActivity empty? if not can you please provide me with code inside it

**Comment by prakasharyaman** [comment]
i think i'm using custom providers and they might be the ones causing the error
`

<provider
    android:name="androidx.startup.InitializationProvider"
    android:authorities="${applicationId}.androidx-startup"
    android:exported="false"
    tools:node="merge">
    <meta-data
        android:name="androidx.work.WorkManagerInitializer"
        android:value="androidx.startup"
        tools:node="remove" />
</provider>


<provider
    android:name="vn.hunghd.flutterdownloader.FlutterDownloaderInitializer"
    android:authorities="${applicationId}.flutter-downloader-init"
    android:exported="false">
    
    <meta-data
        android:name="vn.hunghd.flutterdownloader.MAX_CONCURRENT_TASKS"
        android:value="5" />
</provider>
`

**Comment by prakasharyaman** [comment]
edit: i removed every customisation there was for any type of povider or every other downloading plugin , but it still shows the following problem , though the file is being downloaded in downloads
`I/flutter ( 4696): https://i.redd.it/m4s0l7tl8s091.jpg
D/CompatibilityChangeReporter( 4696): Compat change id reported: 150939131; UID 10291; state: ENABLED
W/System.err( 4696): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
W/System.err( 4696):    at com.example.flutter_file_downloader.core.DownloadCompleterBroadcast.onReceive(DownloadCompleterBroadcast.java:45)
W/System.err( 4696):    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1679)
W/System.err( 4696):    at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
W/System.err( 4696):    at android.os.Handler.handleCallback(Handler.java:938)
W/System.err( 4696):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 4696):    at android.os.Looper.loopOnce(Looper.java:201)
W/System.err( 4696):    at android.os.Looper.loop(Looper.java:288)
W/System.err( 4696):    at android.app.ActivityThread.main(ActivityThread.java:7870)
W/System.err( 4696):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4696):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err( 4696):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
`

**Comment by abdallah-odeh** [comment]
Can you please try now on version **1.0.14**
I updated some code

**Comment by prakasharyaman** [comment]
> Can you please try now on version **1.0.14** I updated some code
sure

**Comment by prakasharyaman** [comment]
**### hey good news** 
It worked the version 1.0.14 worked successfully and now it downloads just fine . 💯 🥇

**Comment by abdallah-odeh** [comment]
Great, thank you for contributing
I really appreciate your help in making this library better

**Comment by prakasharyaman** [comment]
> Great, thank you for contributing I really appreciate your help in making this library better

My pleasure 
![Rhye](https://user-images.githubusercontent.com/63445447/169651960-c3e19182-a256-4934-8ad6-ea31192be926.gif)
