### ISSUE TITLE
[ Feature request ] Max number of continuous downloads 

### ISSUE THREAD

**Issue by p32929** [abdallah-odeh/flutter_files_downloader#2]
Hello, thanks for this amazing library. Is there any way I can limit the number of continuous downloads?
cause, if we try to download a lot of files at once, it makes the app crash or make the phone slower and so on. 
Thanks in advance...

**Comment by abdallah-odeh** [comment]
Hello @p32929, I'm happy that it helps you, currently no there is no limit for consecutive downloads
but I will be working on that feature and I will definitely keep you updated,
Thank you for helping in improving this library

**Comment by p32929** [comment]
Actually, no hurry, Please take your time. & really thanks for the package/library :)

**Comment by abdallah-odeh** [comment]
Breaking news 🚨
I added a new version to control parallelism 
I also added a function to download list of files 

You can update your local version to **flutter_file_downloader: ^1.1.0** to see the changes

If you found a bug or something missing feel free to open issues.

Thank you for helping in improving this plugin.

**Comment by abdallah-odeh** [comment]
Closed for inactive, please if you found a bug or weird behavior don't hesitate opening a new issue or reopen this issue.

**Thank you for your time**

**Comment by p32929** [comment]
Whoa! Awesome works man! Just one thing to add:
The doc seems to be exactly like before. Not sure, how to limit number of simultaneous downloads :/ Can you please also update the documentation? Thanks a lot

**Comment by abdallah-odeh** [comment]
Ooh, I didn't pay attention to that, sure will do, I will update it today inshallah
In the mean time, if you type `FileDownloader.` it will suggest you the public methods,

You can download list of urls using 
`FileDownloader.downloadFiles([...])`

You can enable, disable the log using `FileDownloader.setLogEnabled(true)`

You can limit the consecutive downloads using `FileDownloader.setMaximumParallelDownloads(10 /*Max: 25, Min: 1*/)`

After setting the maximumParallelDownloads, if you called the `downloadFile` 100 times, your downloads will be split to batches

**Comment by p32929** [comment]
Awesome. Can't wait to check it out. Thanks a lot ^_^

**Comment by p32929** [comment]
Thanks a lot man! Really appreciate :)
