### ISSUE TITLE
Is it possible to move the file storage location to an external storage?

### ISSUE THREAD

**Issue by JinyongK** [abdallah-odeh/flutter_files_downloader#3]
I need to save the file to an external storage and use it, but I can't see the part to set the path in this package. Is there any way to save it to external storage?

**Comment by abdallah-odeh** [comment]
Hello @JinyongK,
Unfortunately, this plugin supports downloading only to the downloads directory, you can see the package https://pub.dev/packages/flutter_downloader to download any file to any path you want
