### ISSUE TITLE
open failed

### ISSUE THREAD

**Issue by winnxiegang** [abdallah-odeh/flutter_files_downloader#5]
java.io.FileNotFoundException: /storage/emulated/0/Download/PANDA-5.pdf: open failed: EACCES (Permission denied)
 can i Address the custom file？

**Comment by abdallah-odeh** [comment]
Can you provide the url you downloaded the file from & your android OS version
Could you locate the file in your downloads directory?

**Comment by abdallah-odeh** [comment]
hi @winnxiegang, I tried to reproduce the bug you mentioned, but none worked **Could not reproduce**
OS tested android 7 - 12 & 13 Beta (All emulators)
12 on multiple Samsung devices 
All passed the test case
Can you please provide me with more info
- The url you downloaded
- The OS version & device info
Your help will be highly appreciated

**Comment by abdallah-odeh** [comment]
Close this issue due to lack of activity & information, feel free to reopen it whenever you want
