### ISSUE TITLE
Option to replace file with same name/same URL

### ISSUE THREAD

**Issue by KCWebmaster** [abdallah-odeh/flutter_files_downloader#6]
I was wondering if it was possible or if you could add the option to replace files with the same name or from the same URL.
For example, I download a file from https://myserver.com/image.jpg. Later I want to download this same file. I would like it to replace this file with the same name with the new version.

**Comment by abdallah-odeh** [comment]
Hello @KCWebmaster,
I will be working on that today, will keep you updated.

**Comment by abdallah-odeh** [comment]
Hello @KCWebmaster,
This taking longer time than expected, as some weird behavior occurs,
when downloading the same file more than once & force override, you get multiple instances of the same file with the same name,

Ex: 
lets say you downloaded the files:
https://www.shutterstock.com/image-photo/man-hands-holding-global-network-260nw-1801568002.jpg
https://www.shutterstock.com/image-photo/man-hands-holding-global-network-260nw-1801568002.jpg
- you will have 2 files with the same name & content in the downloads directory (they both working)

but if you downloaded the files and renamed the downloaded file to **test-image:**
https://www.shutterstock.com/image-photo/man-hands-holding-global-network-260nw-1801568002.jpg
https://www.w3schools.com/css/img_forest.jpg
`ISSUES OCCURRED:`
- you will have 2 files with the same name **test-image.jpg**, different content
  but if you refreshed the directory you will notice that both files became the newer version
- if you try to open either of them the Photos app will crash
- if you deleted either file they both get deleted
 
tried on 2 android devices 
android API 33
android API 28

**Comment by abdallah-odeh** [comment]
@KCWebmaster 
after an extensive search, it seems that the app does not have permission to do that!
some resources said that it's up to the browser, it should ask you to replace the file or download it again (which will be downloaded with the same name concatenated with -1 or (1))
some other resources says 

> "It will never overwrite without asking the user first. That would be a horrible feature: any web site could guess what a user has in its downloads folder, and trick the user into downloading an unknown file that would overwrite the file that the user doesn't want to lose"
actually this might be bad, as the user has an important document in the downloads directory, once a file is overwritten the original needed file can never be recovered.

Please if you have any other opinion tell me, I'll close this issue in the weekend unless you have any other idea or workaround.
Have a good one.

**Comment by abdallah-odeh** [comment]
Hello @KCWebmaster,
Since there is not activity in this issue I will close it, feel free to reopen it if you have further discussion.
